### ISSUE TITLE
Address warnings on embedding step

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/word2vec_pipeline#7]
The latest version of gensim gives the following warnings:

```
WARNING:gensim.models.word2vec:under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay
WARNING:gensim.models.word2vec:supplied example count (5918) did not equal expected count (29590)
```

**Comment by RITUait** [comment]
Which parameter to change among size and window to correct this error (consider setting a smaller `batch_words' for smoother alpha decay)
model = gensim.models.Word2Vec (documents, size=100, window=5, min_count=2, workers=10)

**Comment by thoppe** [comment]
Hi @RITUait for me this came up during testing, I wasn't feeding enough data to word2vec for it to learn anything. Once I used a properly sized dataset it went away. Let me know if this is still and problem and I can look at it.

**Comment by RITUait** [comment]
Hii @thoppe, I have 27.7 KB compressed and 127 KB uncompressed text data that consists of c and c++ tutorial text files. My goal is to generate MCQ for these text data. I am making Noun phrases as question word and 4 words that are near it as options(distrators) using word2vec. But my word2vec trained using gensim on c and cpp text files is giving poor results. Can you help me? I would be very much thankful for your help @thoppe .

**Comment by thoppe** [comment]
It sounds like you need a better preprocessing step. This pipeline uses another library we wrote called [NLPre](https://github.com/NIHOPA/NLPre) and we found that it helps our word2vec embeddings a lot. It is, however, tuned for biomedical text, so I'm not sure how it will work for your use case. Different text (like your case of C code), may have a specific step of preprocessing that needs to be done.

**Comment by RITUait** [comment]
Thank you , I will try @thoppe :+1:

**Comment by JingFeliz** [comment]
> Hi @RITUait for me this came up during testing, I wasn't feeding enough data to word2vec for it to learn anything. Once I used a properly sized dataset it went away. Let me know if this is still and problem and I can look at it.

Do you mean that if the data is sufficiently big, the warning will disappear?
